import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import { OcorrenciaProvider } from "./context/OcorrenciaContext";
import Footer from "./components/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <body
    
        className={''}
      >
        <Header/>
                <OcorrenciaProvider>

        {children}
                </OcorrenciaProvider>

      </body>
    </html>
  );
}
